trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: BuildAndDeploy
  displayName: 'Build and Deploy LLMail Inject'
  jobs:
  - job: DeployJob
    displayName: 'Provision and Deploy Resources'
    steps:
    - script: echo "Pipeline started successfully!"
      displayName: 'Initialization Step'

variables:
  azureSubscription: 'AzureConnection'   # Name of your service connection in Azure DevOps
  resourceGroup: 'llmail-inject-rg'      # Your resource group name
  location: 'eastus'                     # Azure region
  storageAccountName: 'llmailstorage123' # Must be globally unique
  functionAppName: 'llmailfuncapp123'    # Must be globally unique
  acrName: 'llmailacr123'                # Must be globally unique
